[package]
name = "bevy_dev"
version = "0.2.0"
authors = ["Vixen <infvix@gmail.com>"]
description = "Dev tools for Bevy Engine"
keywords = ["prototype", "devtools", "textures", "assets"]
categories = ["game-engines", "game-development"]
readme = "README.md"
repository = "https://github.com/Vixenka/bevy_dev"
license-file = "LICENSE"
edition = "2021"

[dependencies]
bevy = { version = "0.13.0", default-features = false, features = [
    "bevy_render",
    "bevy_pbr",
    "png",
] }
random_color = "0.8.0"
rust-embed = "8.3.0"
uuid = "1.7.0"

[dev-dependencies]
bevy = { version = "0.13.0", default-features = false, features = [
    "bevy_winit",
    "tonemapping_luts",
] }
