[package]
name = "bevy_dev"
version = "0.1.0"
authors = ["Vixen <infvix@gmail.com>"]
description = "Dev tools for Bevy Engine"
categories = ["game-engines", "game-development", "tools", "prototype", "bevy"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.12.1", default-features = false, features = [
    "bevy_render",
    "bevy_pbr",
    "png",
] }
bevy_embedded_assets = "0.9.1"
random_color = "0.8.0"
rust-embed = "8.2.0"
uuid = "1.6.1"

[dev-dependencies]
bevy = { version = "0.12", default-features = false, features = ["bevy_winit"] }
